# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-04 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_it', models.CharField(max_length=500)),
                ('title_en', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Project Category',
                'verbose_name_plural': 'Project Categories',
                'ordering': ('title_it',),
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Project Partner',
                'verbose_name_plural': 'Project Partners',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_it', models.CharField(max_length=500)),
                ('title_en', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Project Phase',
                'verbose_name_plural': 'Project Phases',
                'ordering': ('title_it',),
            },
        ),
    ]
