# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-14 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('position', 'title_it'), 'verbose_name': 'Project Category', 'verbose_name_plural': 'Project Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partner',
            name='description_en',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='description_it',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='type',
            field=models.CharField(choices=[(b'Collaborator', 'Collaborator'), (b'Partner', 'Partner')], default=(b'Collaborator', 'Collaborator'), max_length=128),
        ),
        migrations.AddField(
            model_name='partner',
            name='website_url',
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
    ]
