# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-21 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20171118_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='images',
            field=models.ManyToManyField(blank=True, to='website.Image', verbose_name='Images'),
        ),
    ]
